# Use postgres/example user/password credentials

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8081"
  
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.2
    container_name: dbt
    depends_on:
      - db
    tty: true
    stdin_open: true
    volumes:
      
  
  kestra:
